const gamingProducts = [
    {
      name: "HyperX Cloud II",
      price: 699,
      image: "Images/Headsets/hyperX-cloud2.webp",
      category: "Headsets",
      productId: 0,
    },
    {
      name: "Logitech G733",
      price: 799,
      image: "Images/Headsets/logitceh-G733.webp",
      category: "Headsets",
      productId: 1,
    },
    {
      name: "Razer Kraken",
      price: 899,
      image: "Images/Headsets/razer-kraken.webp",
      category: "Headsets",
      productId: 2,
    },
    {
      name: "Steelseries Artic 7",
      price: 1299,
      image: "Images/Headsets/steelseries-arctis-7-2019-tradlost-gamingheadset.jpg",
      category: "Headsets",
      productId: 3,
    },
    {
      name: "Logitech X PRO",
      price: 1999,
      image: "Images/Headsets/logitech-wireless.png",
      category: "Headsets",
      productId: 4,
    },
    {
      name: "Glorious Model-O",
      price: 599,
      image: "Images/Mouse/glorious-model-o.webp",
      category: "Mouse",
      productId: 5,
    },
    {
      name: "Logitech G200",
      price: 799,
      image: "Images/Mouse/logitech-mouse.webp",
      category: "Mouse",
      productId: 6,
    },
    {
      name: "Razer DeathAdder",
      price: 499,
      image: "Images/Mouse/razer-mouse.png",
      category: "Mouse",
      productId: 7,
    },
    {
      name: "Steelseries Sensei",
      price: 500,
      image: "Images/Mouse/steelseries-mouse.png",
      category: "Mouse",
      productId: 8,
    },
    {
      name: "xtrfy w372",
      price: 599,
      image: "Images/Mouse/xtr-mouse1.png",
      category: "Mouse",
      productId: 9,
    },

    {
      name: "HyperX Lightning Wireless",
      price: 1200,
      image: "Images/Keyboards/hyperx-keyboard.webp",
      category: "Keyboards",
      productId: 10,
    },
    {
      name: "Logitech G-PRO",
      price: 1000,
      image: "Images/Keyboards/logitech-keyboard.png",
      category: "Keyboards",
      productId: 11,
    },
    {
      name: "Next G721",
      price: 600,
      image: "Images/Keyboards/next-keyboard.jpg",
      category: "Keyboards",
      productId: 12,
    },
    {
      name: "Razer Huntsman Mini",
      price: 999,
      image: "Images/Keyboards/razer-keyboard.png",
      category: "Keyboards",
      productId: 13,
    },
    {
      name: "Steelseries Apex Pro",
      price: 1200,
      image: "Images/Keyboards/steelseries-keyboard.png",
      category: "Keyboards",
      productId: 14,
    },
    {
      name: "SecretLab Juijutsu - Kaisen",
      price: 3999,
      image: "Images/Chairs/secretlab-anime.webp",
      category: "Gaming-chair",
      productId: 15,
    },
    {
      name: "SecretLab Cloud 9",
      price: 4999,
      image: "Images/Chairs/secretlab-c9.webp",
      category: "Gaming-chair",
      productId: 16,
    },
    {
      name: "SecretLab Dota 2",
      price: 1599,
      image: "Images/Chairs/secretlab-dota2.webp",
      category: "Gaming-chair",
      productId: 17,
    },
    {
      name: "SecretLab DVA",
      price: 3999,
      image: "Images/Chairs/secretlab-gaming-chair.webp",
      category: "Gaming-chair",
      productId: 18,
    },
    {
      name: "SecretLab LoL",
      price: 1999,
      image: "Images/Chairs/secretlab-chair.webp",
      category: "Gaming-chair",
      productId: 19,
    },
  ];
  
  export default gamingProducts;